ALTER TABLE users
  ADD COLUMN gender VARCHAR(10) NULL AFTER age,
  ADD COLUMN imc DECIMAL(19,2) NULL AFTER gender,
  ADD COLUMN tmb DECIMAL(19,2) NULL AFTER imc;

ALTER TABLE goals
  DROP COLUMN imc,
  DROP COLUMN tmb;

ALTER TABLE status
  DROP COLUMN imc,
  DROP COLUMN tmb;