name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: maven:3-eclipse-temurin-25

    steps:
      - uses: actions/checkout@v4
      - run: mvn -B -U -DskipTests clean package
